---
  # TravisCI Docker test role

- name: install the 'C Development Tools and Libraries' package group
  dnf:
    name: '@C Development Tools and Libraries'
    state: present

- name: install the 'Development Libraries' package group
  dnf:
    name: '@Development Libraries'
    state: present

- name: install the latest version of clang
  dnf:
    name: clang
    state: latest

- name: install the latest version of golang
  dnf:
    name: golang
    state: latest

- name: install the latest version of golang net dev
  dnf:
    name: golang-googlecode-net-devel
    state: latest

- name: install the latest version of python2
  dnf:
    name: python2
    state: latest

- name: install the latest version of python3
  dnf:
    name: python3
    state: latest

- name: install the 'Development Tools' package group
  dnf:
    name: '@Development Tools'
    state: present

- name: install the 'Editors' package group
  dnf:
    name: '@Editors'
    state: present

#- name: install the latest version of atom
#  dnf:
#    name: atom
#    state: latest

- name: install the latest version of python-pip
  dnf:
    name: python-pip
    state: latest

- name: install the latest version of snap
  dnf:
    name: snap
    state: latest
